export const auctions:string[] = [
    "ARAI OYAMA",
    "ISUZU KYUSHU",
    "JU AICHI",
    "JU FUKUSHIMA",
    "JU GUNMA",
    "KCAA FUKUOKA",
    "MIRIVE OSAKA",
    "ZIP OSAKA",
    "KCAA YAMAGUCHI",
    "MIRIVE AICHI",
    "MOTA",
    "USS NAGOYA",
    "USS OSAKA",
    "USS SAITAMA",
    "ZERO CHIBA",
]